version: '3'
services:
  node-server:
    build:
      context: ./
      dockerfile: ./docker/node_server/Dockerfile
    image: grpcweb/node-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    links:
      - node-server